import DuistermaatVanDerKallen

/-! Type checks of target propositions and completed general lemmas.
Printing a proposition is not a proof of it. -/

#print DuistermaatVanDerKallen.MinimalNonvanishing
#print DuistermaatVanDerKallen.InfiniteNonvanishing
#print DuistermaatVanDerKallen.RadiusTailObligation
#print DuistermaatVanDerKallen.SpherePathObligation
#check DuistermaatVanDerKallen.finite_of_common_radius
#check DuistermaatVanDerKallen.affineTorus_uniform_gradient
#check DuistermaatVanDerKallen.compact_regular_controlled_region
#check DuistermaatVanDerKallen.scalarLift_right_inverse
#check DuistermaatVanDerKallen.scalarLift_weighted_normSq
#check DuistermaatVanDerKallen.trajectory_radius_bound
#check DuistermaatVanDerKallen.constantTerm_pow_reindex
#check DuistermaatVanDerKallen.minimal_nonvanishing_rank_zero
#check DuistermaatVanDerKallen.restricted_fderiv_norm_sq
#check DuistermaatVanDerKallen.normalizedTangentLift_minimal
#check DuistermaatVanDerKallen.polynomial_restricted_norm
#check DuistermaatVanDerKallen.polynomialVectorField_contDiffAt
#check DuistermaatVanDerKallen.polynomialVectorField_derivative
#check DuistermaatVanDerKallen.polynomialVectorField_embedded_norm
#check DuistermaatVanDerKallen.polynomialVectorField_local_solution
#check DuistermaatVanDerKallen.torusPartial_constraint_eval
#check DuistermaatVanDerKallen.restrictedDifferential_unit_rank_one
#check DuistermaatVanDerKallen.laurentRepresentative_eval
#check DuistermaatVanDerKallen.laurentEval_pow
#check DuistermaatVanDerKallen.laurentEval_hasFDerivAt
#check DuistermaatVanDerKallen.laurent_uniform_gradient
#check DuistermaatVanDerKallen.laurentControlledRegion_isCompact
#check DuistermaatVanDerKallen.laurentControlledRegion_regular
#check DuistermaatVanDerKallen.laurent_integral_curve_base
#check DuistermaatVanDerKallen.laurent_integral_curve_radius_bound
